FROM ubuntu:16.04

RUN apt-get update 
RUN apt-get install -y git python3-pip python3-setuptools
RUN git clone https://github.com/SaGeApps/SiteCX-WebSecScanner.git
WORKDIR SiteCX-WebSecScanner/
RUN pwd
RUN git checkout feature/Neena_CodeUpdations
RUN git pull
WORKDIR Neena/
RUN pip3 install -r requirements.txt 
EXPOSE 7444
RUN PATH=$PATH":/SiteCX-WebSecScanner/Neena"
RUN echo $PATH
ENTRYPOINT [ "python3" ]
CMD [ "program.py" ]














#### OLD
#RUN apt-get update  && \
#        apt-get install -y python3-pip
#COPY ./requirements.txt /opt/WebSecurity/requirements.txt
#WORKDIR /opt/WebSecurity
#RUN pip3 install -r requirements.txt
#COPY * /opt/WebSecurity/
#RUN ls
#EXPOSE 7444
#CMD [ "python3 program.py" ]
