FROM ubuntu:16.04

RUN apt-get update 
RUN apt-get install -y git python3-pip python3-setuptools xvfb curl nmap unzip wget python-pip python-setuptools

RUN cd ~
RUN wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.3/wkhtmltox-0.12.3_linux-generic-amd64.tar.xz
RUN tar vxf wkhtmltox-0.12.3_linux-generic-amd64.tar.xz 
RUN cp wkhtmltox/bin/wk* /usr/local/bin/


#chrome
RUN curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - && \
    echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list && \
    apt-get -yqq update && \
    apt-get -yqq install google-chrome-stable && \
    rm -rf /var/lib/apt/lists/*

RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
RUN apt-get update
RUN apt-get install google-chrome-stable -y




# Install chromedriver for Selenium

RUN CHROMEDRIVER_VERSION="2.42" && \
    mkdir -p /opt/chromedriver-$CHROMEDRIVER_VERSION && \
    curl -sS -o /tmp/chromedriver_linux64.zip http://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip && \
    unzip -qq /tmp/chromedriver_linux64.zip -d /opt/chromedriver-$CHROMEDRIVER_VERSION && \
    rm /tmp/chromedriver_linux64.zip && \
    chmod +x /opt/chromedriver-$CHROMEDRIVER_VERSION/chromedriver && \
    ln -fs /opt/chromedriver-$CHROMEDRIVER_VERSION/chromedriver /usr/local/bin/chromedriver 
 
ENV DISPLAY :20.0
ENV SCREEN_GEOMETRY "1440x900x24"
ENV CHROMEDRIVER_PORT 4444
ENV CHROMEDRIVER_WHITELISTED_IPS "127.0.0.1"
ENV CHROMEDRIVER_URL_BASE ''
ENV CHROMEDRIVER_EXTRA_ARGS ''









RUN git clone https://github.com/SaGeApps/SiteCX-WebSecScanner.git
WORKDIR SiteCX-WebSecScanner/
### RUN pwd
RUN git checkout feature/Neena_CodeUpdations
RUN git pull
WORKDIR Neena/
RUN pip3 install -r requirements-python3.txt
RUN pip install -r requirements-python2.txt  
RUN PATH=$PATH":/SiteCX-WebSecScanner/Neena"
### RUN echo $PATH
#CMD ["git pull"]
#CMD [Xvfb :99 && export DISPLAY=:99]
EXPOSE 7444
ENTRYPOINT [ "python3" ]
CMD [ "program.py" ]
