FROM ubuntu:16.04

RUN apt-get update 
RUN apt-get install -y git python3-pip python3-setuptools xvfb curl nmap


CMD ["git clone https://github.com/SaGeApps/SiteCX-WebSecScanner.git"]
WORKDIR SiteCX-WebSecScanner/
### RUN pwd
RUN git checkout feature/Neena_CodeUpdations
RUN git pull
WORKDIR Neena/
RUN pip3 install -r requirements.txt 
RUN PATH=$PATH":/SiteCX-WebSecScanner/Neena"
### RUN echo $PATH
CMD ["git pull"]
CMD [Xvfb :99 && export DISPLAY=:99]
EXPOSE 7444
ENTRYPOINT [ "python3" ]
CMD [ "program.py" ]
