FROM ubuntu:16.04

RUN apt-get update
RUN apt-get install -y git python3-pip python3-setuptools xvfb curl nmap unzip wget python-pip libxrender1 libfontconfig1

RUN wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.3/wkhtmltox-0.12.3_linux-generic-amd64.tar.xz
RUN tar vxf wkhtmltox-0.12.3_linux-generic-amd64.tar.xz 
RUN cp wkhtmltox/bin/wk* /usr/local/bin/


RUN git clone https://github.com/SaGeApps/SiteCX-WebSecScanner.git
WORKDIR SiteCX-WebSecScanner/
RUN git checkout feature/Anmy_CodeUpdations
RUN git pull

WORKDIR Anmy/

RUN pip3 install -r requirements-python3.txt
RUN pip install -r requirements-python2.txt

EXPOSE 7555

CMD xvfb-run python3 program.py
