FROM ubuntu:16.04

RUN apt-get update 



RUN apt-get install -y git 
RUN apt-get install -y python3-pip 
RUN apt-get install -y python3-setuptools 
RUN apt-get install -y xvfb 
RUN apt-get install -y curl 
RUN apt-get install -y nmap 
RUN apt-get install -y unzip 
RUN apt-get install -y wget 
RUN apt-get install -y python-pip 
RUN apt-get install -y libxrender1

RUN cd ~
RUN wget https://github.com/wkhtmltopdf/wkhtmltopdf/releases/download/0.12.3/wkhtmltox-0.12.3_linux-generic-amd64.tar.xz##
RUN tar vxf wkhtmltox-0.12.3_linux-generic-amd64.tar.xz 
RUN cp wkhtmltox/bin/wk* /usr/local/bin/

RUN git clone https://github.com/SaGeApps/SiteCX-WebSecScanner.git
WORKDIR SiteCX-WebSecScanner/
### RUN pwd
RUN git checkout feature/Anmy_CodeUpdations
RUN git pull
WORKDIR Anmy/
RUN pip3 install -r requirements-python3.txt
RUN pip install -r requirements-python2.txt
### RUN echo $PATH
### CMD ["git pull"]
CMD [Xvfb :0 && export DISPLAY=:0]
EXPOSE 7555
ENTRYPOINT [ "python3" ]
CMD [ "program.py" ]
